### PR TITLE
Fix and update to PR #3 - Adapt to bevy latest

### PR DESCRIPTION
**Pull request by BlackPhlox**
Fixed issue with pr and updated docs to bevy 0.5, added example for bevy 0.5, added CI parameter to fix syn issue.

### CODE REVIEW

**Comment by BlackPhlox** [comment]
image

Damn

**Comment by BlackPhlox** [comment]
Fixed the issue, I'll stabilize CI with next commit.

**Comment by BlackPhlox** [comment]
Yay 🎉

**Comment by HydrogenC** [comment]
> Yay 🎉

Congratulations! You are an expert in CI!

**Comment by BlackPhlox** [comment]
> 
> Congratulations! You are an expert in CI!

Thanks but you can clearly see by my most recent commits that I am definitely not an expert 😅

**Comment by sburris0** [comment]
Wow, looks great guys! Thanks!

**Pull request merged**
