### PR TITLE
Allow key bindings customization

### PR DESCRIPTION
**Pull request by tesfabpel**
Hi, 
I added a (very) simple way to configure key bindings.
I hope I did everything alright.

### CODE REVIEW

**Comment by BlackPhlox** [comment]
Hi @tesfabpel :wave: Keybindings have already been discussed in [this issue (#7) ](https://github.com/sburris0/bevy_flycam/issues/7#issuecomment-826261751) and was deemed to add too much complexity to the project. That is of course unless @sburris0 has changed his opinion on this.

**Comment by TheCarpetMerchant** [comment]
@BlackPhlox @sburris0 Not having key bindings is unnecessarily limiting. Here I am, making a branch of this project solely because of this reason. Please reconsider this decision, if only for the purpose of international use.
There does not need to be added complexity, as Key bindings could simply be added to `MovementSettings`, with WASD as the default.
If you do not which to change `MovementSettings`, creating a simple `KeyBindings` struct used as a resource and used in `player_move` is perfectly fine too.

**Comment by BlackPhlox** [comment]
@TheCarpetMerchant I'll follow up on this Sunday, giving Spencer some time to respond to this.

**Comment by sburris0** [comment]
I hadn't considered international use. I agree this is worthwhile to help non-US keyboard users

Dec 15, 2022 8:52:55 AM TheCarpetMerchant ***@***.***>:

**Comment by BlackPhlox** [comment]
Cool, I'll see if I can merge the changes since this pr was made prior to 0.9

**Pull request merged**
